OC.L10N.register(
    "files_accesscontrol",
    {
    "No rule given" : "لا يوجد أي اشتراط",
    "Block access to a file" : "منع الوصول إلى ملف",
    "File is accessed" : "الملف يُمكن الوصول إليه",
    "File access control" : "التحكم في الوصول إلى الملفات",
    "Control access to files based on conditions" : "التحكم في الوصول إلى الملفات بناءً على اشتراطات",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, MIME type and request time to group membership, tags, user agent and more.\n\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "تطبيق نكست كلاود للتحكم في الوصول إلى الملفات يُمكّن المشرفين من حماية البيانات من وصول غير المُخوّلين إليها أو تعديلها. \n\n## كيف يعمل التطبيق\nيُمكن للمشرف إنشاء و إدارة مجموعات من الاشتراطات. كُلُّ واحدة من هذه المجموعات تتكون من اشتراطٍ واحدٍ أو أكثر. إذا انطبقت جميع اشتراطات المجموعة تنطبق المجموعة و عندها يُمنع الوصول إلى البيانات أو رفع بياناتٍ إلى المُجلّد المعني.\nتتنوع الاشتراطات من عنوان المستخدم IP إلى نوع الملف MIME إلى وقت الطلب إلى عضوية المستخدم في المجموعات المختلفة إلى اللاصقات إلى وكيل المستخدم إلى غير ذلك.\n\nمثال لذلك: يُمنع الوصول إلى ملفات MS Excel/XLSX التي تملكها مجموعة قسم الموارد البشرية \"Human Resources\" إذا كانت الطلبات واردة من عنوان IP من خارج شبكة المؤسسة. مثال آخر: يٌمنع تحديث الملفات التي يزيد حجمها عن 512 ميغا بايت على الطلبة أعضاء مجموعة السنة الأولى \"1st year\".\n\nللمزيد حول التحكم في الوصول إلى الملفت، أنظر:  [https://nextcloud.com/workflow](https://nextcloud.com/workflow) ."
},
"nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 && n%100<=99 ? 4 : 5;");
