OC.L10N.register(
    "files_accesscontrol",
    {
    "No rule given" : "Nezadáno žádné pravidlo",
    "Block access to a file" : "Zablokovat přístup k souboru",
    "File is accessed" : "K souboru je přistupováno",
    "File access control" : "Řízení přístupu k souborům",
    "Control access to files based on conditions" : "Řídí přístup k souborům na základě podmínek",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, MIME type and request time to group membership, tags, user agent and more.\n\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "Nextcloud aplikace „Řízení přístupu k souborům“ umožňuje správcům chránit data před neoprávněným přístupem nebo úpravám.\n\n## Jak to funguje\nSprávce může vytvořit a spravovat sadu skupin pravidel. Každá z těchto skupin je tvořena jedním nebo více pravidly. Pokud všechna pravidla odpovídají, bude skupina odpovídat požadavku a přístup je na základě toho odepřen nebo je nahrání zablokováno. Hlediska pravidel jsou od IP adresa, MIME typu a času požadavku po  členství ve skupině, štítku, user agent a další.\n\nPříkladem by bylo odepření přístupu k MS Excel/XLSX souborům vlastněným skupinou „Personalni oddeleni“, ke kterým je přistupováno z IP adresy, která se nenachází ve vnitřní síti společnosti nebo blokování nahrávání souborů větších než 512 MB studenty ze skupiny „Prvni rocnik“.\n\nVíce o „Řízení přístupu k souborům“ je k dispozici na [https://nextcloud.com/workflow](https://nextcloud.com/workflow)"
},
"nplurals=4; plural=(n == 1 && n % 1 == 0) ? 0 : (n >= 2 && n <= 4 && n % 1 == 0) ? 1: (n % 1 != 0 ) ? 2 : 3;");
