OC.L10N.register(
    "files_accesscontrol",
    {
    "No rule given" : "Κανένας δεδομένος κανόνας",
    "Block access to a file" : "Αποκλεισμός πρόσβασης σε ένα αρχείο",
    "File is accessed" : "Το αρχείο είναι προσβάσιμο",
    "File access control" : "Αρχεία ελέγχου πρόσβασης",
    "Control access to files based on conditions" : "Ελέγξτε την πρόσβαση στα αρχεία με βάση τις συνθήκες",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, MIME type and request time to group membership, tags, user agent and more.\n\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "Η εφαρμογή File Access Control του Nextcloud επιτρέπει στους διαχειριστές να προστατεύουν δεδομένα από μη εξουσιοδοτημένη πρόσβαση ή τροποποιήσεις.\n\n## Πώς λειτουργεί\nΟ διαχειριστής μπορεί να δημιουργήσει και να διαχειριστεί ένα σύνολο ομάδων κανόνων. Κάθε μία από τις ομάδες κανόνων αποτελείται από έναν ή περισσότερους κανόνες. Εάν όλοι οι κανόνες μιας ομάδας ισχύουν, η ομάδα ταιριάζει με το αίτημα και η πρόσβαση απορρίπτεται ή η μεταφόρτωση αποκλείεται. Τα κριτήρια των κανόνων κυμαίνονται από διεύθυνση IP, τύπο MIME και χρόνο αιτήματος έως συμμετοχή σε ομάδες, ετικέτες, user agent και περισσότερα.\n\nΈνα παράδειγμα θα ήταν η άρνηση πρόσβασης σε αρχεία MS Excel/XLSX που ανήκουν στην ομάδα \"Ανθρώπινο Δυναμικό\" που προσπελαύνονται από μια διεύθυνση IP που δεν ανήκει στο εσωτερικό δίκτυο της εταιρείας ή ο αποκλεισμός μεταφορτώσεων αρχείων μεγαλύτερων των 512 MB από μαθητές στην ομάδα \"1ου έτους\".\n\nΜάθετε περισσότερα για το File Access Control στο [https://nextcloud.com/workflow](https://nextcloud.com/workflow)"
},
"nplurals=2; plural=(n != 1);");
