OC.L10N.register(
    "files_accesscontrol",
    {
    "No rule given" : "Κανένας δεδομένος κανόνας",
    "Block access to a file" : "Αποκλεισμός πρόσβασης σε ένα αρχείο",
    "File is accessed" : "Το αρχείο είναι προσβάσιμο",
    "File access control" : "Αρχεία ελέγχου πρόσβασης",
    "Control access to files based on conditions" : "Ελέγξτε την πρόσβαση στα αρχεία με βάση τις συνθήκες",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, mimetype and request time to group membership, tags, user agent and more.\n\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "Η εφαρμογή ελέγχου πρόσβασης αρχείων του Nextcloud επιτρέπει στους διαχειριστές να προστατεύουν τα δεδομένα από μη εξουσιοδοτημένη πρόσβαση ή τροποποιήσεις.\n\n## Πώς λειτουργεί\nΟ διαχειριστής μπορεί να δημιουργήσει και να διαχειριστεί ένα σύνολο ομάδων κανόνων. Κάθε μία από τις ομάδες κανόνων αποτελείται από έναν ή περισσότερους κανόνες. Εάν όλοι οι κανόνες μιας ομάδας θεωρούνται αληθείς, το αίτημα ελέγχεται και η πρόσβαση απορρίπτεται ή η φόρτωση αποκλείεται. Τα κριτήρια κανόνων ορίζονται από τη διεύθυνση IP, τον τύπο mime και τον χρόνο αιτήματος για την ιδιότητα μέλους, τις ετικέτες, τον χρήστη και άλλα.\n\nΈνα παράδειγμα θα ήταν να αρνούνται την πρόσβαση σε αρχεία MS Excel / XLSX που ανήκουν στην ομάδα \"Ανθρώπινοι πόροι\" που έχουν πρόσβαση από μια διεύθυνση IP όχι στο εσωτερικό εταιρικό δίκτυο ή να εμποδίζουν μεταφορτώσεις αρχείων μεγαλύτερων από 512 mb από τους μαθητές στην ομάδα \"1ου έτους\" .\n\nΜάθετε περισσότερα σχετικά με τον έλεγχο πρόσβασης αρχείων στο [https://nextcloud.com/workflow](https://nextcloud.com/workflow)",
    "Restrict access to files based on factors such as filetype, user group memberships, time and more." : "Περιορίστε την πρόσβαση στα αρχεία βάσει παραγόντων όπως τύπος αρχείου, ιδιότητες μέλους της ομάδας χρηστών, χρόνος και πολλά άλλα.",
    "Each rule group consists of one or more rules. A request matches a group if all rules evaluate to true. If a request matches at least one of the defined groups, the request is blocked and the file content can not be read or written." : "Kάθε ομάδα από κανόνες μπορεί να περιλαμβάνει έναν ή  περισσότερους κανόνες. Ένα αίτημα είναι αποδεκτό στην ομάδα αν και μόνον αν είναι αληθές. Αν το αίτημα ταιριάζει έστω και σε μια από τις καθορισμένες ομάδες, τότε το αίτημα δέχεται αποκλεισμό και το περιεχόμενο αρχείο δεν είναι δυνατόν να διαβαστεί ή να προσπελαστεί.",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, mimetype and request time to group membership, tags, user agent and more.\n\t\t\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\t\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "Η εφαρμογή ελέγχου πρόσβασης αρχείων του Nextcloud επιτρέπει στους διαχειριστές να προστατεύουν τα δεδομένα από μη εξουσιοδοτημένη πρόσβαση ή τροποποιήσεις.\n\n## Πώς λειτουργεί\nΟ διαχειριστής μπορεί να δημιουργήσει και να διαχειριστεί ένα σύνολο ομάδων κανόνων. Κάθε μία από τις ομάδες κανόνων αποτελείται από έναν ή περισσότερους κανόνες. Εάν όλοι οι κανόνες μιας ομάδας θεωρούνται αληθείς, το αίτημα ελέγχεται και η πρόσβαση απορρίπτεται ή η φόρτωση αποκλείεται. Τα κριτήρια κανόνων ορίζονται από τη διεύθυνση IP, τον τύπο mime και τον χρόνο αιτήματος για την ιδιότητα μέλους, τις ετικέτες, τον χρήστη και άλλα.\n\t\t\nΈνα παράδειγμα θα ήταν να αρνούνται την πρόσβαση σε αρχεία MS Excel / XLSX που ανήκουν στην ομάδα \"Ανθρώπινοι πόροι\" που έχουν πρόσβαση από μια διεύθυνση IP όχι στο εσωτερικό εταιρικό δίκτυο ή να εμποδίζουν μεταφορτώσεις αρχείων μεγαλύτερων από 512 mb από τους μαθητές στην ομάδα \"1ου έτους\" .\n\t\nΜάθετε περισσότερα σχετικά με τον έλεγχο πρόσβασης αρχείων στο [https://nextcloud.com/workflow](https://nextcloud.com/workflow)"
},
"nplurals=2; plural=(n != 1);");
