OC.L10N.register(
    "files_accesscontrol",
    {
    "No rule given" : "No se dado ninguna regla",
    "File access control" : "Control de acceso a los archivos",
    "Restrict access to files based on factors such as filetype, user group memberships, time and more." : "Restringe el acceso a archivos basándose en factores como el tipo de archivo, la pertenencia a grupos de usuarios, el tiempo y más.",
    "Each rule group consists of one or more rules. A request matches a group if all rules evaluate to true. If a request matches at least one of the defined groups, the request is blocked and the file content can not be read or written." : "Cada grupo de reglas consiste en una o más reglas. Una petición coincide con un grupo si todas las reglas se evalúan como verdaderas. Si una petición coincide al menos con uno de los grupos definidos, la petición es bloqueada y el contenido del archivo no se puede leer ni escribir.",
    "Control access to files based on conditions" : "Control del acceso a archivos basado en condiciones",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, mimetype and request time to group membership, tags, user agent and more.\n\t\t\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\t\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "La app de Control de acceso a Archivos de Nextcloud permite a los administradores proteger los datos de accesos o modificaciones no autorizadas.\n\n## Cómo trabaja\nEl administrador puede crear y manejar un conjunto de grupos de reglas. Cada grupo de reglas consiste en una o más reglas. SI todas las reglas de un grupo se verifican, el grupo detecta la petición uy se niega el acceso o se bloquea la subida. Los criterios de las reglas van desde la dirección IP, tipo MIME y hora de petición hasta la pertenencia a grupos, etiquetas, agente de usuario y más.\n\t\t\nUn ejemplo sería negar el acceso a los archivos de Excel/.xlsx propiedad del grupo \"Recursos Humanos\" a los que se accedan desde una IP que no esté en la red interna de la compañía, o bloquear la subida de archivos mayores de 512 Mb por parte de estudantes en el grupo \"Primer año\".\n\t\nDescubre más sobre el Control de acceso a archivos en [https://nextcloud.com/workflow](https://nextcloud.com/workflow).",
    "Nextcloud's File Access Control app enables administrators to create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied. The rules criteria range from IP address, to user groups, collaborative tags and some more." : "La app Control de acceso a archivos de Nextcloud permite a los administradores crear y manejar un conjunto de grupos de reglas. Si todas las reglas de un grupo se cumplen, el grupo coincide con la petición y se deniega el acceso. El rango de criterios de las reglas van desde la dirección IP a grupos de usuarios, etiquetas colaborativas y algunos más.",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, mimetype and request time to group membership, tags, user agent and more.\n\t\t\nAn example would be to deny access to Excell/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\t\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "El Control de acceso a archivos de Nextcloud permite a los administradores proteger los datos de accesos o modificaciones no autorizados.\n\n## Cómo trabaja\nEl administrador puede crear y manejar un conjunto de grupos de reglas. Cada uno de los grupos de reglas consiste en una o más reglas. Si todas las reglas de un grupo se cumplen, el grupo coincide con la petición y el acceso se niega o se bloquea la subida. El rango de criterios para las reglas va desde las direcciones IP, tipos mime y hora de la petición hasta pertenencia a grupos, etiquetas, agente de usuario y más.\n\t\t\nUn ejemplo sería denegar el acceso a los archivos de Excel (.xlsx) propiedad del grupo \"Recursos Humanos\" al acceder desde una IP que no pertenezca a la red interna de la compañía o bloquear subidas de archivos mayores de 512 Mb por parte de estudiantes en el grupo \"Primer curso\"\n\t\nAprende más sobre el Control de acceso a archivos en [https://nextcloud.com/workflow](https://nextcloud.com/workflow)"
},
"nplurals=2; plural=(n != 1);");
