OC.L10N.register(
    "files_accesscontrol",
    {
    "No rule given" : "No hay una regla establecida",
    "Block access to a file" : "Bloquear el acceso a un archivo ",
    "File is accessed" : "El archivo es accedido ",
    "File access control" : "Control de acceso de archivos",
    "Control access to files based on conditions" : "Controlar el acceso a archivos basado en condiciones",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, MIME type and request time to group membership, tags, user agent and more.\n\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "La aplicación de Control de Acceso a Archivos de Nextcloud permite a los administradores proteger los datos contra el acceso o modificaciones no autorizadas.\n\n## Cómo funciona\nEl administrador puede crear y gestionar un conjunto de grupos de reglas. Cada grupo de reglas consiste en una o más reglas. Si todas las reglas de un grupo son verdaderas, el grupo coincide con la solicitud y se deniega el acceso o se bloquea la carga. Los criterios de las reglas van desde la dirección IP, el tipo de MIME y el tiempo de la solicitud hasta la pertenencia a grupos, etiquetas, agente de usuario y más.\n\nUn ejemplo sería denegar el acceso a los archivos de MS Excel/XLSX propiedad del grupo \"Recursos Humanos\" cuando se accede desde una IP que no pertenece a la red interna de la empresa, o bloquear las cargas de archivos mayores de 512 MB realizadas por estudiantes del grupo \"1er año\".\n\nObtenga más información sobre el Control de Acceso a Archivos en [https://nextcloud.com/workflow](https://nextcloud.com/workflow)"
},
"nplurals=3; plural=n == 1 ? 0 : n != 0 && n % 1000000 == 0 ? 1 : 2;");
