OC.L10N.register(
    "files_accesscontrol",
    {
    "No rule given" : "No hay una regla establecida",
    "File access control" : "Control de acceso de archivos",
    "Control access to files based on conditions" : "Controla el acceso a archivos con base en condiciones",
    "Restrict access to files based on factors such as filetype, user group memberships, time and more." : "Restrinje el acceso a archivos con base en factores tales como tipo de archivo, pertenencia a gurpos de usuarios, tiempo y más. ",
    "Each rule group consists of one or more rules. A request matches a group if all rules evaluate to true. If a request matches at least one of the defined groups, the request is blocked and the file content can not be read or written." : "Cada grupo de reglas consiste en una o más reglas. Una solicitud coincide con un grupo cuando el resultado de todas las reglas es verdadero. Si una solicitud coincide con al menos uno de los grupos definidos, la solicitud es bloqueada y el contendio del archivo no se puede leer o escribir. ",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, mimetype and request time to group membership, tags, user agent and more.\n\t\t\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\t\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "La aplicación de Control de Acceso a Archivos le permite a los adminsitradores proteger datos de un acceso o modificación no autorizados.\n\n## Cómo funciona\nEl adminsitrador puede crear y administrar un juego de grupos de reglas. Cada grupo de reglas contiene una o más reglas. Si todas las reglas de un grupo se evaluan como positivas, el grupo coincide con la solicitud y el acceso es denegado o la carga es bloqueada. El criterio de las reglas abarca desde dirección IO, tipo MIME y tiempo de solicitud hasta pertenencia a un grupo, etiquetas, agente del usuario y más.\n\t\t\nUn ejemplo sería denegar acceso a archivos de MS Excel / XLSX propiedad del grupo de \"Recursos Humanos\" accedidos desde una IP fuera de la red corporativa interna o bien bloquear cargas de mas de 512 Mb por estudiantes en el grupo de \"1er año\".\n\t\nConoce más acerca del Control de Acceso a Archivos en [https://nextcloud.com/workflow](https://nextcloud.com/workflow)"
},
"nplurals=2; plural=(n != 1);");
