OC.L10N.register(
    "files_accesscontrol",
    {
    "No rule given" : "Ez dago araurik",
    "Block access to a file" : "Fitxategi baterako atzipena blokeatu",
    "File is accessed" : "Fitxategia atzituta",
    "File access control" : "Fitxategiaren sarbide kontrola",
    "Control access to files based on conditions" : "Fitxategien atzipena baldintzekin mugatu",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, MIME type and request time to group membership, tags, user agent and more.\n\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "Nextclouden Fitxategien Sarbide kontrolerako aplikazioak, fitxategiak baimen gabeko atzipen edo aldaketatik babesteko aukera ematen dio kudeatzaileei.\n\n## Nola dabil hau\nAdministratzaileak arau-talde multzo bat sortu eta kudea dezake. Arau-talde bakoitza arau bat edo gehiagoz osatuta dago. Talde baten arau guztiak betetzen badira, taldea eskaerarekin bat dator eta sarbidea blokeatu edo fitxategiaren igoera blokeatu egiten da Arau-irizpideak IP helbidea, MIME mota eta taldekide izateko denbora eskatu, etiketak, erabiltzaile-agentea eta abar..\n\nAdibide bat hauxe litzateke: \"Giza baliabideak\" taldearen jabetzako MS Excel/XLSX fitxategiei sarbidea ukatzea enpresaren barneko sarean ez dagoen IP batetik sartuta edo \"1. mailako\" taldeko ikasleek 512 mb baino handiagoak diren fitxategien igoerak blokeatzea. \n\nLortu informazio gehiago Fitxategien Sarbideen Kontrolari buruz [https://nextcloud.com/workflow](https://nextcloud.com/workflow)"
},
"nplurals=2; plural=(n != 1);");
