OC.L10N.register(
    "files_accesscontrol",
    {
    "No rule given" : "Aucune règle donnée",
    "Block access to a file" : "Bloquer l'accès à un fichier",
    "File is accessed" : "Le fichier est consulté",
    "File access control" : "Contrôle d'accès aux fichiers",
    "Control access to files based on conditions" : "Le contrôle des fichiers est basé sur des conditions",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, mimetype and request time to group membership, tags, user agent and more.\n\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "L'application de contrôle d' accès aux fichiers de Nextcloud' permet aux administrateurs de protéger les données contre tout accès ou modification.\n\n## Comment ça marche ?\nL'administrateur peut créer et gérer un ensemble de groupes de règles. Chacun de ces groupes se compose d'une ou plusieurs règles. Si toutes les règles d'un groupe correspondent aux restrictions souhaitées, le groupe applique alors ses règles à la requête reçue et l'accès est alors refusé ou bien le téléversement est bloqué. Les critères varient et vont des restrictions sur les adresses IP, les types MIME, l'heure de demande d'adhésion à un groupe pour en être membre, lestags, l'agent utilisateur (User-Agent), etc\n\nPar exemple : refuser l'accès aux documents MS Excel/XLSX appartenant au groupe \"Ressources humaines\" accdés par une adresse IP ne faisant pas partie du réseau de l'entreprise interne, ou bien bloquer les téléversements de fichiers dépssant les 512 Mo par des étudiants du groupe \"1ère année\".\n\nPour en savoir plus sur l'application de contrôle d'accès aux fichiers :  [https://nextcloud.com/fr_FR/workflow/](https://nextcloud.com/fr_FR/workflow/)",
    "Restrict access to files based on factors such as filetype, user group memberships, time and more." : "Limiter l'accès aux fichiers basés sur des éléments comme le type de fichier, les membres de groupe utilisateur, l'heure et plus encore.",
    "Each rule group consists of one or more rules. A request matches a group if all rules evaluate to true. If a request matches at least one of the defined groups, the request is blocked and the file content can not be read or written." : "Chaque groupe de règles est constitué d'une ou plusieurs règles. Une requête correspond à un groupe si toutes les règles évaluées sont vraies. Si une requête correspond à au moins un groupe définit, la requête est bloquée et le contenu du fichier ne peut pas être lu ou écrit.",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, mimetype and request time to group membership, tags, user agent and more.\n\t\t\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\t\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "L'application de contrôle d'accès aux fichiers de Nextcloud permet aux administrateurs de protéger les données contre les accès non autorisés ou les modifications.\n\n## Comment ça marche\nL'administrateur peut créer et gérer un ensemble de groupes de règles. Chacun des groupes de règles comprend une ou plusieurs règles. Si toutes les règles d'un groupe sont vraies, le groupe correspond à la demande et l'accès est refusé ou le téléchargement est bloqué. Les critères de règles vont de l'adresse IP, du type MIME et de l'heure de la demande à l'appartenance à un groupe, des étiquettes, de l'agent utilisateur, et plus encore.\n\nUn exemple serait de refuser l'accès aux fichiers MS Excel / XLSX appartenant au groupe \"Ressources Humaines\" accédé depuis une IP ne faisant pas partie du réseau interne de l'entreprise, ou de bloquer les téléversements de fichiers supérieurs à 512 Mo par les étudiants du groupe \"1ère année\" .\n\nEn savoir plus sur le contrôle d'accès aux fichiers sur [https://nextcloud.com/workflow](https://nextcloud.com/workflow)]"
},
"nplurals=2; plural=(n > 1);");
