OC.L10N.register(
    "files_accesscontrol",
    {
    "No rule given" : "Non se indicou ningunha regra",
    "Block access to a file" : "Bloquear o acceso a un ficheiro",
    "File is accessed" : "Accedeuse a este ficheiro",
    "File access control" : "Control de acceso aos ficheiros",
    "Control access to files based on conditions" : "Control de acceso a ficheiros segundo certas condicións.",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, MIME type and request time to group membership, tags, user agent and more.\n\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "A aplicación de control de acceso a ficheiros de Nextcloud permítelle á administración da instancia protexer os datos de accesos ou modificacións non autorizadas.\n\n## Como traballa\nA  administración pode crear e xestionar un conxunto de grupos de regras. Cada grupo de regras consiste nunha ou máis regras. Se todas as regras dun grupo se verifican, o grupo detecta a solicitude e nega o acceso ou bloquea o envío. Os criterios das regras van dende o enderezo IP, tipo MIME e hora de solicitude ata a pertenza a grupos, etiquetas, axente de usuario e outras.\n\t\t\nUn exemplo sería negar o acceso aos ficheiros de MS Excel/.XLSX propiedade do grupo «Recursos humanos» aos que se accedan dende unha IP que non estea na rede interna da empresa, ou bloquear o envío de ficheiros maiores de 512 Mb por parte de alumnos no grupo «Primeiro ano».\n\t\nObteña máis información sobre o control de acceso a ficheiros en [https://nextcloud.com/workflow](https://nextcloud.com/workflow)."
},
"nplurals=2; plural=(n != 1);");
