OC.L10N.register(
    "files_accesscontrol",
    {
    "No rule given" : "Non se indicou ningunha regra",
    "Block access to a file" : "Bloquear o acceso a un ficheiro",
    "File is accessed" : "Accedeuse a este ficheiro",
    "File access control" : "Control de acceso aos ficheiros",
    "Control access to files based on conditions" : "Control de acceso a ficheiros segundo certas condicións.",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, mimetype and request time to group membership, tags, user agent and more.\n\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "A aplicaciónde control de acceso a ficheiros de Nextcloud permítelle aos administradores protexer os datos de accesos ou modificacións non autorizadas.\n\n## Como traballa\nO administrador pode crear e manexar un conxunto de grupos de regras. Cada grupo de regras consiste nunha ou máis regras. Se todas as regras dun grupo se verifican, o grupo detecta a solicitude e nega o acceso ou bloquea o envío. Os criterios das regras van dende o enderezo IP, tipo MIME e hora de solicitude ata a pertenza a grupos, etiquetas, axente de usuario e outras.\n\nUn exemplo sería negar o acceso aos ficheiros de MS Excel/.XLSX propiedade do grupo «Recursos humanos» aos que se accedan dende unha IP que non estea na rede interna da empresa, ou bloquear o envío de ficheiros maiores de 512 Mb por parte de alumnos no grupo «Primeiro ano».\n\nObteña máis información sobre o control de acceso a ficheiros en [https://nextcloud.com/workflow](https://nextcloud.com/workflow).",
    "Restrict access to files based on factors such as filetype, user group memberships, time and more." : "Restrinxe o acceso a ficheiros segundo factores como o tipo de ficheiro, a pertenza a grupos de usuarios, a hora e máis.",
    "Each rule group consists of one or more rules. A request matches a group if all rules evaluate to true. If a request matches at least one of the defined groups, the request is blocked and the file content can not be read or written." : "Cada grupo de regras consiste nunha ou máis regras. Unha solicitude coincide cun grupo se todas as regras se avalían como verdadeiras. Se unha petición coincide cando menos cun dos grupos definidos, a petición é bloqueada e o contido do ficheiro non pode se lido nin escrito.",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, mimetype and request time to group membership, tags, user agent and more.\n\t\t\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\t\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "A aplicaciónde control de acceso a ficheiros de Nextcloud permítelle aos administradores protexer os datos de accesos ou modificacións non autorizadas.\n\n## Como traballa\nO administrador pode crear e manexar un conxunto de grupos de regras. Cada grupo de regras consiste nunha ou máis regras. Se todas as regras dun grupo se verifican, o grupo detecta a solicitude e nega o acceso ou bloquea o envío. Os criterios das regras van dende o enderezo IP, tipo MIME e hora de solicitude ata a pertenza a grupos, etiquetas, axente de usuario e outras.\n\t\t\nUn exemplo sería negar o acceso aos ficheiros de MS Excel/.XLSX propiedade do grupo «Recursos humanos» aos que se accedan dende unha IP que non estea na rede interna da empresa, ou bloquear o envío de ficheiros maiores de 512 Mb por parte de alumnos no grupo «Primeiro ano».\n\t\nObteña máis información sobre o control de acceso a ficheiros en [https://nextcloud.com/workflow](https://nextcloud.com/workflow)."
},
"nplurals=2; plural=(n != 1);");
