OC.L10N.register(
    "files_accesscontrol",
    {
    "No rule given" : "Nema propisanog pravila",
    "Block access to a file" : "Blokiraj pristup datoteci",
    "File is accessed" : "Datoteci je pristupljeno",
    "File access control" : "Kontrola pristupa datotekama",
    "Control access to files based on conditions" : "Kontroliraj pristup datotekama na temelju uvjeta",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, mimetype and request time to group membership, tags, user agent and more.\n\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "Nextcloudova aplikacija za kontrolu pristupa datotekama omogućuje administratorima da zaštite podatke od neovlaštenog pristupa ili izmjena.\n\n## Kako radi\nAdministrator može stvoriti i upravljati skupinom pravila. Svaka skupina pravila sastoji se od jednog ili više pravila. Ako su sva pravila iz skupine istinita, skupina odgovara zahtjevu i pristup je odbijen ili je otpremanje blokirano. Kriteriji za pravila kreću se od IP adrese, mimetypea i vremena zahtjeva do članstva u grupi, oznaka, korisničkog agenta itd.\n\nPrimjerice, zabrana pristupa datotekama MS Excel/XLSX u vlasništvu grupe „Ljudski resursi” kojima pristupa IP adresa koja nije u unutarnjoj mreži tvrtke ili blokiranje otpreme datoteka većih od 512 MB za studente iz grupe „1. godina”.\n\nSaznajte više informacija o kontroli pristupa datotekama na [https://nextcloud.com/workflow](https://nextcloud.com/workflow)",
    "Restrict access to files based on factors such as filetype, user group memberships, time and more." : "Ograničite pristup datotekama na temelju čimbenika kao što su vrsta datoteka, članstvo u korisničkoj grupi, vrijeme itd.",
    "Each rule group consists of one or more rules. A request matches a group if all rules evaluate to true. If a request matches at least one of the defined groups, the request is blocked and the file content can not be read or written." : "Svaka skupina pravila sastoji se od jednog ili više pravila. Zahtjev odgovara grupi ako se sva pravila ocijene kao istinita. Ako zahtjev odgovara barem jednoj od definiranih skupina, zahtjev je blokiran i sadržaj datoteke ne može se čitati niti pisati.",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, mimetype and request time to group membership, tags, user agent and more.\n\t\t\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\t\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "Nextcloudova aplikacija za kontrolu pristupa datotekama omogućuje administratorima da zaštite podatke od neovlaštenog pristupa ili izmjena.\n\n## Kako radi\nAdministrator može stvoriti i upravljati skupinom pravila. Svaka skupina pravila sastoji se od jednog ili više pravila. Ako su sva pravila iz skupine istinita, skupina odgovara zahtjevu i pristup je odbijen ili je otpremanje blokirano. Kriteriji za pravila kreću se od IP adrese, mimetypea i vremena zahtjeva do članstva u grupi, oznaka, korisničkog agenta itd.\n\t\t\nPrimjerice, zabrana pristupa datotekama MS Excel/XLSX u vlasništvu grupe „Ljudski resursi” kojima pristupa IP adresa koja nije u unutarnjoj mreži tvrtke ili blokiranje otpreme datoteka većih od 512 mb za studente iz grupe „1. godina”.\n\t\nSaznajte više informacija o kontroli pristupa datotekama na [https://nextcloud.com/workflow](https://nextcloud.com/workflow)"
},
"nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;");
