OC.L10N.register(
    "files_accesscontrol",
    {
    "No rule given" : "Nincs szabály megadva",
    "Block access to a file" : "Egy fájl elérésének blokkolása",
    "File is accessed" : "A fájl elérhető",
    "File access control" : "Fájl hozzáférés-vezérlés",
    "Control access to files based on conditions" : "Vezérelje a fájlok elérését feltételek alapján",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, mimetype and request time to group membership, tags, user agent and more.\n\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "A Nextcloud „Fájlhozzáférés-vezérlés” alkalmazás lehetővé teszi, hogy a rendszergazdák megvédjék az adatokat a jogosulatlan hozzáféréstől és módosítástól.\n\n## Hogyan működik\nA rendszergazda szabálycsoportokat hozhat létre és kezelhet. Minden egyes szabálycsoport egy vagy több szabályból áll. Ha a csoport összes szabálya teljesül, és a csoport megfelel a kérésnek, akkor az elérés vagy a letöltés elutasításra kerül. A szabályok feltételei IP-címek, MIME-típusok, kérési idők, csoporttagságok, címkék, felhasználói ügynökök és egyebek lehetnek.\n\nEgy példa az lehet, hogy meg akarja akadályozni, hogy az „Emberi erőforrások” csoport MS Excel/XLSX fájljait olyan IP-címekről érjék el, melyek nem a belső céges hálózatban vannak; vagy meg akarja akadályozni, hogy az „Elsőévesek” csoport tanulói 512 MB-nál nagyobb fájlokat töltsenek fel.\n\nTudjon meg többet a Fájlhozzáférés-vezérlésről a [https://nextcloud.com/workflow](https://nextcloud.com/workflow) oldalon.",
    "Restrict access to files based on factors such as filetype, user group memberships, time and more." : "Korlátozza a fájlokhoz való hozzáférést olyan tényezők alapján, mint a fájltípus, a felhasználói csoporttagságok, az idő és így tovább.",
    "Each rule group consists of one or more rules. A request matches a group if all rules evaluate to true. If a request matches at least one of the defined groups, the request is blocked and the file content can not be read or written." : "Minden szabály csoport egy vagy több szabályból áll. Egy kérés akkor egyezik a csoporttal ha minden szabály kiértékelése igaz. Ha egy kérés legalább egy definiált csoporttal egyezik, a kérés blokkolva lesz és a fájl tartalma nem lesz írható vagy olvasható.",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, mimetype and request time to group membership, tags, user agent and more.\n\t\t\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\t\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "A Nextcloud „Fájlhozzáférés-vezérlés” alkalmazás lehetővé teszi, hogy a rendszergazdák megvédjék az adatokat a jogosulatlan hozzáféréstől és módosítástól.\n\n## Hogyan működik\nA rendszergazda szabálycsoportokat hozhat létre és kezelhet. Minden egyes szabálycsoport egy vagy több szabályból áll. Ha a csoport összes szabálya teljesül, és a csoport megfelel a kérésnek, akkor az elérés vagy a letöltés elutasításra kerül. A szabályok feltételei IP-címek, MIME-típusok, kérési idők, csoporttagságok, címkék, felhasználói ügynökök és egyebek lehetnek.\n\nEgy példa az lehet, hogy meg akarja akadályozni, hogy az „Emberi erőforrások” csoport MS Excel/XLSX fájljait olyan IP-címekről érjék el, melyek nem a belső céges hálózatban vannak; vagy meg akarja akadályozni, hogy az „Elsőévesek” csoport tanulói 512 MB-nál nagyobb fájlokat töltsenek fel.\n\nTudjon meg többet a Fájlhozzáférés-vezérlésről a [https://nextcloud.com/workflow](https://nextcloud.com/workflow) oldalon."
},
"nplurals=2; plural=(n != 1);");
