OC.L10N.register(
    "files_accesscontrol",
    {
    "No rule given" : "Nenurodyta taisyklė",
    "Block access to a file" : "Blokuoti prieigą prie failo",
    "File is accessed" : "Prie failo prieinama",
    "File access control" : "Failų prieigos valdymas",
    "Control access to files based on conditions" : "Valdyti prieigą prie failų remiantis sąlygomis",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, MIME type and request time to group membership, tags, user agent and more.\n\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "„Nextcloud“ programa „File Access Control“ leidžia administratoriams apsaugoti duomenis nuo neteisėtos prieigos ar pakeitimų.\n\n## Kaip tai veikia\nAdministratorius gali kurti ir valdyti taisyklių grupių rinkinį. Kiekvieną taisyklių grupę sudaro viena ar daugiau taisyklių. Jei visos grupės taisyklės yra tenkinamos, grupė atitinka užklausą ir prieiga yra uždrausta arba įkėlimas yra blokuojamas. Taisyklių kriterijai apima IP adresą, MIME tipą ir užklausos laiką, grupės narystę, žymes, vartotojo agentą ir dar daugiau.\n\nPavyzdžiui, galima uždrausti prieigą prie „Žmogiškųjų išteklių“ grupei priklausančių MS Excel/XLSX failų, jei prieiga vykdoma iš IP adreso, kuris nepriklauso įmonės vidiniam tinklui, arba užblokuoti „1-ojo kurso“ grupės studentų failų, didesnių nei 512 MB, įkėlimą.\n\nSužinokite daugiau apie failų prieigos kontrolę [https://nextcloud.com/workflow](https://nextcloud.com/workflow)"
},
"nplurals=4; plural=(n % 10 == 1 && (n % 100 > 19 || n % 100 < 11) ? 0 : (n % 10 >= 2 && n % 10 <=9) && (n % 100 > 19 || n % 100 < 11) ? 1 : n % 1 != 0 ? 2: 3);");
