OC.L10N.register(
    "files_accesscontrol",
    {
    "No rule given" : "Не е зададено правило",
    "Block access to a file" : "Блокирај пристап до датотека",
    "File is accessed" : "Пристапено до датотеката",
    "File access control" : "Контрола на пристап до датотеки",
    "Control access to files based on conditions" : "Контрола на пристап до датотеки базирано на услови",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, MIME type and request time to group membership, tags, user agent and more.\n\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "Апликацијата за контрола на пристап до датотеки им овозможува на администраторите да ги штитат податоците од неовластен пристап или измени.\n\n## Како работи\nАдминистраторот може да креира и управува со збир на групни правила. Секое групно правило се состои од едно или повеќе правила. Ако сите правила на една група важат, групата одговара на барањето и пристапот е одбиен или прикачувањето е блокирано. Критериумите за правила се движат од IP адреса, вид на датотека и време на барање до групно членство, ознаки, кориснички агент и повеќе.\n\nПример би бил да се одбие пристапот до датотеките MS Excel / XLSX во сопственост на групата „Човечки ресурси“, пристапено од IP што не е на мрежата на внатрешната компанија или да блокира поставување датотеки поголеми од 512 mb од студенти во групата „1-ва година“ .\n\nПовеќе за Контролата за пристап до датотеки на [https://nextcloud.com/workflow] (https://nextcloud.com/workflow)"
},
"nplurals=2; plural=(n % 10 == 1 && n % 100 != 11) ? 0 : 1;");
