OC.L10N.register(
    "files_accesscontrol",
    {
    "No rule given" : "Nie podano żadnej reguły",
    "Block access to a file" : "Zablokuj dostęp do pliku",
    "File is accessed" : "Plik jest dostępny",
    "File access control" : "Kontrola dostępu do pliku",
    "Control access to files based on conditions" : "Kontroluj dostęp do plików w oparciu o warunki",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, MIME type and request time to group membership, tags, user agent and more.\n\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "Aplikacja Nextcloud File Access Control umożliwia administratorom ochronę danych przed nieautoryzowanym dostępem lub modyfikacjami.\n\n## Jak to działa\nAdministrator może tworzyć reguły grup i nimi zarządzać. Każda reguła grupy może składać się z jednej lub więcej reguł. Jeśli wszystkie reguły grupy są spełnione, a grupa odpowiada danemu żądaniu, to dostęp lub przesyłanie jest od razu zablokowane. Kryteria obejmują zakres poprzez adres IP, typ MIME, czasu zgłoszenia przypisania do grupy, etykiet, różnych czynników użytkownika i wiele innych.\n\nPrzykładem może być odmowa dostępu do plików MS Excel/XLSX należących do grupy \"Zasoby ludzkie\", do których dostęp w wewnętrznej sieci firmowej jest uzyskiwany z adresu IP lub blokowanie przesyłania plików większych niż 512 MB przez studentów z grupy \"pierwszego roku\" .\n\nDowiedz się więcej o kontroli dostępu do pliku na [https://nextcloud.com/workflow](https://nextcloud.com/workflow)"
},
"nplurals=4; plural=(n==1 ? 0 : (n%10>=2 && n%10<=4) && (n%100<12 || n%100>14) ? 1 : n!=1 && (n%10>=0 && n%10<=1) || (n%10>=5 && n%10<=9) || (n%100>=12 && n%100<=14) ? 2 : 3);");
