OC.L10N.register(
    "files_accesscontrol",
    {
    "No rule given" : "Nenhuma regras fornecida",
    "Block access to a file" : "Bloquear acesso ao arquivo",
    "File is accessed" : "Arquivo acessado",
    "File access control" : "Controle de acesso a arquivos",
    "Control access to files based on conditions" : "Controlar o acesso a arquivos com base em condições",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, mimetype and request time to group membership, tags, user agent and more.\n\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "O aplicativo Controle de Acesso a Arquivos Nextcloud permite que os administradores protejam os dados contra acesso ou modificações não autorizadas.\n\n## Como funciona\nO administrador pode criar e gerenciar um conjunto de grupos de regras. Cada um dos grupos de regras consiste em uma ou mais regras. Se todas as regras de um grupo forem verdadeiras, o grupo corresponderá à solicitação e o acesso será negado ou o upload será bloqueado. Os critérios de regras variam de endereço IP, mimetype, tempo de solicitação para associação ao grupo, tags, agente de usuário e muito mais.\n\nUm exemplo seria negar o acesso aos arquivos do MS Excel/XLSX pertencentes ao grupo \"Recursos Humanos\" acessado de um IP que não está na rede interna da empresa ou bloquear o upload de arquivos maiores que 512 mb pelos alunos do grupo \"1º ano\".\n\nSaiba mais sobre o Controle de Acesso a Arquivos em [https://nextcloud.com/workflow](https://nextcloud.com/workflow)",
    "Restrict access to files based on factors such as filetype, user group memberships, time and more." : "Acesso restrito a arquivos baseado em fatores como tipo de arquivo, membros de grupo de usuários, horário e mais.",
    "Each rule group consists of one or more rules. A request matches a group if all rules evaluate to true. If a request matches at least one of the defined groups, the request is blocked and the file content can not be read or written." : "Cada grupo de regras consiste em uma ou mais regras. Uma solicitação corresponderá a um grupo se todas as regras avaliadas forem verdadeiras. Se uma solicitação corresponde pelo menos um dos grupos definidos, a solicitação será bloqueada e o conteúdo do arquivo não poderá ser lido ou alterado.",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, mimetype and request time to group membership, tags, user agent and more.\n\t\t\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\t\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "O Controle de Acesso a Arquivos do Nextcloud permite que administradores protejam os dados contra acesso não autorizado ou modificações.\n\n## Como funciona\nO administrador pode criar e gerenciar um conjunto de grupos de regras. Cada um dos grupos de regras consiste em uma ou mais regras. Se todas as de um grupo forem verdadeiras, o grupo baterá com a solicitação e o acesso ou envio será negado. Os critérios de regras variam por endereço IP, tipo MIME, tempo de solicitação para associação ao grupo, tags, agente do usuário e muito mais.\n\t\t\nUm exemplo seria negar o acesso a arquivos MS Excel/XLSX pertencentes ao grupo \"Recursos Humanos\" acessados a partir de um IP externo à empresa ou bloquear envios de arquivos maiores que 512 MB pelos alunos do grupo \"1º ano\" .\n\t\nSaiba mais sobre o Controle de Acesso a Arquivos em [https://nextcloud.com/workflow](https://nextcloud.com/workflow)"
},
"nplurals=2; plural=(n > 1);");
