OC.L10N.register(
    "files_accesscontrol",
    {
    "No rule given" : "Nenhuma regra fornecida",
    "Block access to a file" : "Bloquear acesso a um arquivo",
    "File is accessed" : "Arquivo é acessado",
    "File access control" : "Controle de acesso a arquivos",
    "Control access to files based on conditions" : "Controlar o acesso a arquivos com base em condições",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, MIME type and request time to group membership, tags, user agent and more.\n\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "O aplicativo Controle de Acesso do Arquivo do Nextcloud permite que os administradores protejam os dados contra acesso ou modificações não autorizadas.\n\n## Como funciona\nO administrador pode criar e gerenciar um conjunto de grupos de regras. Cada um dos grupos de regras consiste em uma ou mais regras. Se todas as regras de um grupo forem verdadeiras, o grupo corresponde à solicitação e o acesso está sendo negado ou o upload é bloqueado. Os critérios das regras variam de endereço IP, tipo MIME e tempo de solicitação para associação de grupo, etiquetas, agente de usuário e muito mais.\n\nUm exemplo seria negar o acesso a arquivos MS Excel/XLSX pertencentes ao grupo \"Recursos Humanos\" acessados de um IP que não está na rede interna da empresa ou bloquear uploads de arquivos maiores que 512 mb por alunos do grupo \"1º ano\" .\n\nSaiba mais sobre o controle de acesso a arquivos em [https://nextcloud.com/workflow](https://nextcloud.com/workflow)"
},
"nplurals=3; plural=(n == 0 || n == 1) ? 0 : n != 0 && n % 1000000 == 0 ? 1 : 2;");
