OC.L10N.register(
    "files_accesscontrol",
    {
    "No rule given" : "Peruna règula frunida",
    "Block access to a file" : "Bloca s'atzessu a unu documentu",
    "File is accessed" : "Su documentu est abertu",
    "File access control" : "Controllu de atzessu a su documentu",
    "Control access to files based on conditions" : "Su controllu de s'atzessu a is documentos basadu in cunditziones",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, mimetype and request time to group membership, tags, user agent and more.\n\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "S'aplicatzione de controllu de atzessu a is documentos de Nextcloud permitit a is amministradores de amparare is datos dae atzessos no autorizados o dae càmbios.\n\n## Comente funtzionat\nChie amministrat podet creare e gestire unas cantas grupu de règulas. Cada grupu de règulas tenet una o prus règulas. Chi totu is règulas de su grupu sunt vàlidas, su grupu acumprit is rechestas e s'atzessu est negadu o su carrigamentu si blocat. Is critèrios de i règulas vàriant dae s'indirizu IP, documentos MIME e su tempus de sa rechesta pro s'adesione a su grupu, etichetas, user agent e àteras cosas.\n\nUnu esèmpiu diat èssere de negare s'atzessu a documentos de MS Excel/XLSX de se grupu \"Resursas Umanas\" chi benit dae un'IP esternu a sa rete de s'azienda o de blocare is carrigamentos de documentos prus mannos de 512 mb pro parte de istudiantes in su grupu \"Primu annu\"\n\nIscoberri de prus subra su Controllu de Atzessu a is Documentos in [https://nextcloud.com/workflow](https://nextcloud.com/workflow)"
},
"nplurals=2; plural=(n != 1);");
