OC.L10N.register(
    "files_accesscontrol",
    {
    "No rule given" : "Žiadne vybrané pravidlo",
    "Block access to a file" : "Zablokovať prístup k súboru",
    "File is accessed" : "Pristupujem k súboru",
    "File access control" : "Správa prístupov k súborom",
    "Control access to files based on conditions" : "Kontrolovanie prístupu k súborom na základe podmienok",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, MIME type and request time to group membership, tags, user agent and more.\n\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "Aplikácia File Access Control od Nextcloud umožňuje správcom chrániť dáta pred neoprávneným prístupom alebo úpravami.\n\n## Ako to funguje\nAdministrátor môže vytvoriť a spravovať skupinu pravidiel. Každá zo skupín pravidiel pozostáva z jedného alebo viacerých pravidiel. Ak platia všetky pravidlá skupiny, pre skupinu ktorá sa zhoduje s požiadavkou, je prístup odmietnutý alebo je nahrávanie zablokované. Kritériá pravidiel siahajú od adresy IP, typu MIME a času požiadavky až po členstvo v skupine, štítky, užívateľského agenta a ďalšie.\n\nPríkladom môže byť odmietnutie prístupu k súborom MS Excel/XLSX, ktoré vlastní skupina „Ľudské zdroje“, ku ktorým sa pristupuje z IP adresy mimo internej podnikovej siete, alebo blokovanie nahrávania súborov väčších ako 512 MB študentmi skupiny „1. ročník“. .\n\nĎalšie informácie o riadení prístupu k súborom nájdete na [https://nextcloud.com/workflow](https://nextcloud.com/workflow)"
},
"nplurals=4; plural=(n % 1 == 0 && n == 1 ? 0 : n % 1 == 0 && n >= 2 && n <= 4 ? 1 : n % 1 != 0 ? 2: 3);");
