OC.L10N.register(
    "files_accesscontrol",
    {
    "No rule given" : "Žiadne vybrané pravidlo",
    "Block access to a file" : "Zablokovať prístup k súboru",
    "File is accessed" : "Pristupujem k súboru",
    "File access control" : "Správa prístupov k súborom",
    "Control access to files based on conditions" : "Kontrolovanie prístupu k súborom na základe podmienok",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, mimetype and request time to group membership, tags, user agent and more.\n\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "Aplikácia File Access Control od Nextcloudu umožňuje správcom chrániť údaje pred neoprávneným prístupom alebo úpravami.\n\n## Ako to funguje\nSprávca môže vytvoriť a spravovať skupiny pravidiel. Každá zo skupín pravidiel pozostáva z jedného alebo viacerých pravidiel. Ak sú všetky pravidlá skupiny v platnosti, skupina sa zhoduje s požiadavkou a prístup je odmietnutý alebo nahrávanie je zablokované. Kritériá pravidiel sa pohybujú od adresy IP, typu mimetypu a času žiadosti po členstvo v skupine, značky, agenta používateľa a ďalšie.\n\nPríkladom by bolo zamietnutie prístupu k súborom MS Excel / XLSX patriacim skupine „Ľudské zdroje“ z IP mimo vnútornej siete spoločnosti, alebo blokovanie nahrávania súborov väčších ako 512 mb študentmi v skupine „1. rok“. \n\nViac informácií o File Access Control nájdete na [https://nextcloud.com/workflow](https://nextcloud.com/workflow)"
},
"nplurals=4; plural=(n % 1 == 0 && n == 1 ? 0 : n % 1 == 0 && n >= 2 && n <= 4 ? 1 : n % 1 != 0 ? 2: 3);");
