OC.L10N.register(
    "files_accesscontrol",
    {
    "No rule given" : "Није дато ниједно правило",
    "Block access to a file" : "Блокирај приступ фајлу",
    "File is accessed" : "Фајлу приступљено",
    "File access control" : "Права приступа фајловима",
    "Control access to files based on conditions" : "Контролишите приступ фајловима на основу услова",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, mimetype and request time to group membership, tags, user agent and more.\n\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "Некстклаудова апликација за Контролу Приступа омогућава администраторима да заштите податке од неовлашћеног приступа или измена.\n\n## Како ради\nНекстклаудова апликација за Контролу Приступа омогућава администраторима да креирају и да управљају скуповима групних правила. Свака група правила садржи једно или више правила. Ако су испуњена сва правила у групи, група се поклапа са захтевом и приступ је одбијен. Критеријуми за правила су од опсега IP адреса, корисничких група, заједничких ознака, типу веб читача и још много тога.\n\nПример би био забрана приступа MS Excel/XLSX фајловима чији је власник \"Кадровска служба\" када им се приступа са IP адресе која није из фирминог опсега или забрана отпремања фајлова већих од 512MB студентима из групе \"Бруцоши\".\n\nСазнајте више о Контроли Приступа фајловима на [https://nextcloud.com/workflow](https://nextcloud.com/workflow)"
},
"nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);");
