OC.L10N.register(
    "files_accesscontrol",
    {
    "No rule given" : "Hakuna kanuni iliyotolewa",
    "Block access to a file" : "Zuia uingiaji kwenye faili",
    "File is accessed" : "Faili linaingiliwa",
    "File access control" : "Udhibiti wa uingiaji wa faili ",
    "Control access to files based on conditions" : "Dhibiti ufikiaji wa faili kulingana na hali",
    "Nextcloud's File Access Control app enables administrators to protect data from unauthorized access or modifications.\n\n## How it works\nThe administrator can create and manage a set of rule groups. Each of the rule groups consists of one or more rules. If all rules of a group hold true, the group matches the request and access is being denied or the upload is blocked. The rules criteria range from IP address, MIME type and request time to group membership, tags, user agent and more.\n\nAn example would be to deny access to MS Excel/XLSX files owned by the \"Human Resources\" group accessed from an IP not on the internal company network or to block uploads of files bigger than 512 mb by students in the \"1st year\" group.\n\nLearn more about File Access Control on [https://nextcloud.com/workflow](https://nextcloud.com/workflow)" : "Programu ya Nextcloud ya Kudhibiti Ufikiaji wa Faili huwezesha wasimamizi kulinda data dhidi ya ufikiaji au marekebisho yasiyoidhinishwa.\n\n## Jinsi inavyofanya kazi\nMsimamizi anaweza kuunda na kudhibiti seti ya vikundi vya sheria. Kila moja ya vikundi vya sheria ina sheria moja au zaidi. Ikiwa sheria zote za kikundi ni kweli, kikundi kinalingana na ombi na ufikiaji unakataliwa au upakiaji umezuiwa. Vigezo vya sheria huanzia kwenye anwani ya IP, aina ya MIME na muda wa ombi la uanachama wa kikundi, lebo, wakala wa mtumiaji na zaidi.\n\nMfano utakuwa kukataa ufikiaji wa faili za MS Excel/XLSX zinazomilikiwa na kikundi cha \"Rasilimali Watu\" zinazofikiwa kutoka kwa IP isiyo kwenye mtandao wa kampuni ya ndani au kuzuia upakiaji wa faili kubwa kuliko mb 512 na wanafunzi katika kikundi cha \"mwaka wa 1\".\n\nPata maelezo zaidi kuhusu Udhibiti wa Ufikiaji wa Faili kwenye [https://nextcloud.com/workflow](https://nextcloud.com/workflow)\n \n \n "
},
"nplurals=2; plural=(n != 1);");
